Repository zauberzeug/rosys, pull requests merged in 2024-02, with the labels that each got.

#79 readding cameras first removes old route
  rosys/vision/image_route.py
Labels: bug

#83 Esp activation
  rosys/hardware/robot_brain.py
Labels: enhancement

#82 Detector upload
  rosys/vision/detections.py
  rosys/vision/detector.py
  rosys/vision/detector_hardware.py
  rosys/vision/detector_simulation.py
  rosys/vision/image.py
Labels: enhancement

#81 Integration of IMU using quaternions
  poetry.lock
  pyproject.toml
  rosys/geometry/rotation.py
  rosys/hardware/__init__.py
  rosys/hardware/imu.py
  tests/test_geometry.py
Labels: enhancement

#86 Add docstring
  rosys/hardware/robot.py
Labels: documentation
