Repository zauberzeug/rosys, pull requests merged in 2024-08, with the labels that each got.

#163 Allow images up to 10 mb for the detector
  rosys/vision/detector_hardware.py
Labels: enhancement

#161 Allow parallelizing coroutines with different sleep intervals
  rosys/automation/parallelize.py
  tests/test_automations.py
Labels: bug

#164 Rename integration fixture to "rosys_integration"
  rosys/testing/fixtures.py
  tests/test_cameras.py
  tests/test_event.py
  tests/test_mjpeg_camera.py
  tests/test_time.py
Labels: enhancement

#166 Add relative_direction function to Pose
  rosys/geometry/pose.py
Labels: enhancement

#158 Fix p0 flashing
  rosys/hardware/lizard_firmware.py
  rosys/hardware/robot_brain.py
Labels: bug

#153 Chained Pose Transformations
  docs/examples/coordinate_frames.md
  docs/examples/coordinate_frames.webp
  docs/src/example_coordinate_frames.py
  examples/camera_arm/main.py
  mkdocs.yml
  rosys/geometry/__init__.py
  rosys/geometry/frame3d_registry.py
  rosys/geometry/object3d.py
  rosys/geometry/point3d.py
  rosys/geometry/pose.py
  rosys/geometry/pose3d.py
  rosys/geometry/rotation.py
  rosys/rosys.py
  rosys/testing/__init__.py
  rosys/testing/helpers.py
  rosys/vision/__init__.py
  rosys/vision/calibration.py
  rosys/vision/camera/calibratable_camera.py
  rosys/vision/camera/camera.py
  rosys/vision/camera_objects_.py
  rosys/vision/camera_scene_object.py
  rosys/vision/simulated_camera/simulated_camera.py
  tests/test_camera_calibration.py
  tests/test_geometry_2d.py
  tests/test_geometry_3d.py
Labels: enhancement

#167 Remove run.cpu_bound for rotation computation
  rosys/vision/camera_objects_.py
Labels: bug

#168 Provide auto-updated `Odometer.prediction_frame`
  examples/camera_arm/main.py
  rosys/driving/odometer.py
Labels: enhancement

#169 Add `SimulatedCalibratableCamera`
  docs/src/example_coordinate_frames.py
  rosys/vision/__init__.py
  rosys/vision/simulated_camera/__init__.py
  rosys/vision/simulated_camera/simulated_calibratable_camera.py
Labels: enhancement

#171 Use new frame resolving in `DetectorSimulation`
  rosys/vision/detector_simulation.py
Labels: enhancement

#172 Do not stop after driving a spline
  examples/hello_bot/main.py
  rosys/driving/driver.py
  tests/test_automations.py
Labels: enhancement

#175 Provide property to get first connected camera
  rosys/vision/camera_provider.py
Labels: enhancement

#176 Allow specifying the info string drawn on every frame of a timelapse video
  rosys/analysis/timelapse_recorder.py
Labels: enhancement

#174 Some house keeping
  poetry.lock
  pyproject.toml
  rosys/analysis/tracking.py
  rosys/automation/parallelize.py
  rosys/vision/camera/camera.py
  tests/test_automations.py
Labels: enhancement

#177 Use NiceGUI's run.io_bound and run.cpu_bound
  rosys/run.py
Labels: bug

#178 Add support for Python 3.12
  .github/workflows/publish.yml
  .github/workflows/pytest.yml
  Dockerfile
  poetry.lock
  pyproject.toml
  rosys/analysis/kpi_logger.py
  rosys/automation/automation.py
  rosys/automation/automator.py
Labels: enhancement

#180 Don't emit ROBOT_MOVED in handle_detection
  rosys/driving/odometer.py
Labels: bug

#179 More modular functions to use for export and import of persistence modules
  rosys/persistence/__init__.py
  rosys/persistence/registry.py
  rosys/persistence/ui.py
Labels: enhancement

#170 Improve documentation for `calibration.project_to_image`
  rosys/geometry/object3d.py
  rosys/vision/calibration.py
  tests/test_camera_calibration.py
  tests/test_geometry_3d.py
Labels: documentation

#181 Fix docker image
  Dockerfile
  docker-compose.yml
Labels: bug

#185 Add point_3d property to pose3d
  rosys/geometry/pose3d.py
Labels: enhancement
