Repository zauberzeug/rosys, pull requests merged in 2025-08, with the labels that each got.

#316 Upgrade to Python 3.13 as the default version, drop support for Python 3.10
  .github/workflows/publish.yml
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  Dockerfile
  docker-compose.yml
  poetry.lock
  pyproject.toml
  rosys.code-workspace
  rosys/analysis/kpi_buckets.py
  rosys/analysis/kpi_logger.py
  rosys/event.py
  rosys/geometry/object3d.py
  rosys/geometry/pose3d.py
  rosys/hardware/gnss.py
  rosys/pathplanning/area.py
  rosys/persistence/persistable.py
  rosys/run.py
  rosys/testing/log_configuration.py
  rosys/vision/camera/calibratable_camera.py
  rosys/vision/camera/camera.py
  rosys/vision/image.py
  rosys/vision/image_rotation.py
  rosys/vision/mjpeg_camera/motec_settings_interface.py
  rosys/vision/rtsp_camera/rtsp_camera.py
  rosys/vision/rtsp_camera/rtsp_device.py
Labels: enhancement, breaking change

#317 Custom reprojection tolerance
  rosys/vision/calibration.py
Labels: enhancement

#318 Expand IMU simulation by roll and pitch
  rosys/hardware/imu.py
Labels: enhancement

#321 Stop driver when spline is too short and stop_at_end is True
  rosys/driving/driver.py
Labels: bug

#322 Restructure GNSS developer ui to make it more flexible
  rosys/hardware/gnss.py
Labels: enhancement

#327 Allow customization of the KPI page
  rosys/analysis/kpi_page_.py
Labels: enhancement

#325 Correctly handle EStop events
  rosys/hardware/estop.py
Labels: bug
