Repository zauberzeug/rosys, pull requests merged in 2025-05, with the labels that each got.

#280 Add configurable logging level and nicegui keyword arguments to notify function
  rosys/rosys.py
Labels: enhancement

#285 Improve GNSS message processing to avoid time discrepancies between NMEA messages and RoSys
  rosys/hardware/gnss.py
Labels: enhancement

#266 Introduce a new `Persistable` mixin
  docs/examples/camera_arm/main.py
  docs/examples/persistence/README.md
  docs/examples/persistence/main.py
  rosys/analysis/kpi_logger.py
  rosys/automation/schedule.py
  rosys/config.py
  rosys/core.py
  rosys/pathplanning/path_planner.py
  rosys/persistence/__init__.py
  rosys/persistence/backup_schedule.py
  rosys/persistence/import_export.py
  rosys/persistence/persistable.py
  rosys/persistence/persistent_module.py
  rosys/persistence/registry.py
  rosys/persistence/ui.py
  rosys/rosys.py
  rosys/vision/camera_provider.py
  rosys/vision/mjpeg_camera/mjpeg_camera_provider.py
  rosys/vision/rtsp_camera/rtsp_camera_provider.py
  rosys/vision/simulated_camera/simulated_camera_provider.py
  rosys/vision/usb_camera/usb_camera_provider.py
  tests/test_persistence.py
Labels: enhancement

#287 Handle missing NMEA timestamp
  rosys/hardware/gnss.py
Labels: bug

#284 Implement new esp disabling
  rosys/hardware/robot_brain.py
Labels: enhancement

#290 Clear `Persistable` instances after test
  rosys/persistence/backup_schedule.py
  rosys/rosys.py
Labels: bug

#289 Generate breaking change warnings for release notes
  fetch_milestone.py
Labels: documentation

#292 Improve ESP ready state handling
  rosys/automation/app_controls_.py
  rosys/hardware/__init__.py
  rosys/hardware/bms.py
  rosys/hardware/robot_brain.py
Labels: enhancement

#298 Make the driver's minimum spline length configurable
  rosys/driving/driver.py
Labels: enhancement
